name: keto
favicon: null
layout_spectrum: 0.8599559487774968
typography_spectrum: 0.22201634314842522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.12683831015601754
  lightness: 0.6457761761266738
  saturation: 0.13962960778735578
  rhythmicContrast: 0.41831506905145943
purpose: []
